### ISSUE TITLE
(Ua)² 

### ISSUE THREAD

**Issue by MariusVanDerWijden** [initc3/babySNARK#2]
Hey guys, thanks for the interesting read! 

I have a question about the first sentence on page 3 of the pdf. There you say "We will also write (Ua) o (a) as (Ua)²". I think this should be "(Ua) o (Ua) as (Ua)²" 
and in the last paragraph you say "That is instead (Ua)² = 1" not "That is instead (Ua)² = →1"

**Comment by amiller** [comment]
good suggestions, thanks!
fixed in 6635b7 (hard to see without checking in the .tex for now)
